<a href="https://colab.research.google.com/github/MacarenaQuijadaG/ETL/blob/main/Pandas2_Alura_5_BancoDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Alura 5 - Leyendo banco de Datos**

**Creando un banco de datos local**

In [1]:
import sqlalchemy

In [2]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [3]:
engine = create_engine('sqlite:///:memory:')

**Escribiendo en un banco de datos**

In [4]:
import pandas as pd

In [6]:
archivo = 'clientes_banco.csv'

In [7]:
datos = pd.read_csv(archivo)

In [9]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

**Crear Tabla**

In [10]:
datos.to_sql('clientes', engine, index=False)

438463

In [11]:
inspector = inspect(engine)

In [12]:
print(inspector.get_table_names())

['clientes']

**Leyendo una consulta SQL**

In [25]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renta = "Empleado"'

In [26]:
empleados = pd.read_sql(sql=text(query), con = engine.connect())

In [27]:
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [28]:
empleados.to_sql('empleados', con = engine.connect(), index=False)

226059

In [29]:
pd.read_sql_table('empleados', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [32]:
pd.read_sql_table('empleados', con = engine.connect(), columns=['ID_Cliente','Grado_estudio','Rendimiento_anual'])

        ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
226054     6837905  Nivel intermedio           355050.0
226055     6837906  Nivel intermedio           355050.0
226056     6839936  Nivel intermedio           135000.0
226057     6840222  Nivel intermedio           103500.0
226058     6842885  Nivel intermedio           121500.0

[226059 rows x 3 columns]

**Actualizando un banco de datos**

In [33]:
query = 'SELECT * FROM clientes'

In [34]:
pd.read_sql(sql=text(query), con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [36]:
#Borrando registros
from sqlalchemy.exc import SQLAlchemyError
query = "DELETE FROM clientes WHERE ID_Cliente=5008804"
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ",r_set.rowcount)

#Registros borrados:  1

In [37]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [38]:
#Actualizando registros
query = 'UPDATE clientes SET Grado_estudio="Nivel superior" WHERE ID_Cliente=5008808'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  1

In [39]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel superior,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [40]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']